spring.application.name=camila-acosta-mobilefix-v2

# =======================================
# SUPABASE (POSTGRESQL) CONFIG - Con Pooler
# =======================================
# Datos tomados de tu captura de Supabase
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.pxithsybbfijxypyrvbh
spring.datasource.password=militaseeee*

# =======================================
# JPA/HIBERNATE CONFIG
# =======================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
