package dao.impl;

import config.DbConfig;
import dao.interfaces.BookDao;
import domain.Book;
import exception.DataAccessException;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class BookDaoImpl implements BookDao {

    @Override
    public Book create(Book book) throws DataAccessException {
        String sql = "INSERT INTO book (title, author, isbn, stock, status) VALUES (?,?,?,?,?)";

        // Prepare the statement to enter the data, also add the return generated keys to return the id generated by the database
        try (Connection connection = DbConfig.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            preparedStatement.setString(1, book.getTitle());
            preparedStatement.setString(2, book.getAuthor());
            preparedStatement.setString(3, book.getIsbn());
            preparedStatement.setInt(4, book.getStock());
            preparedStatement.setBoolean(5, book.isStatus());

            if (preparedStatement.executeUpdate() == 0) {
                throw new DataAccessException("The creation of the book failed");
            }

            try (ResultSet objRestKeys = preparedStatement.getGeneratedKeys()) {
                if (objRestKeys.next()) {
                    book.setIdBook(objRestKeys.getInt(1));
                } else {
                    throw new DataAccessException("Failed to create book, could not get ID");
                }
            }
            return book;
        } catch (SQLException e) {
            throw new DataAccessException("Error creating book in the database", e);
        }
    }

    @Override
    public Optional<Book> findById(Integer id) throws DataAccessException {
        String sql = "SELECT * FROM book WHERE id_book = ?";

        try (Connection connection = DbConfig.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {

            preparedStatement.setInt(1, id);
            ResultSet objRest = preparedStatement.executeQuery();

            if (objRest.next()) {
                Book book = new Book();
                book.setIdBook(objRest.getInt("id_book"));
                book.setTitle(objRest.getString("title"));
                book.setAuthor(objRest.getString("author"));
                book.setIsbn(objRest.getString("isbn"));
                book.setStock(objRest.getInt("stock"));
                book.setStatus(objRest.getBoolean("status"));

                return Optional.of(book);
            }

        } catch (SQLException e) {
            throw new DataAccessException("Error searching for book by ID", e);
        }
        return Optional.empty();
    }

    @Override
    public Optional<Book> findByIsbn(String isbn) throws DataAccessException {
        String sql = "SELECT * FROM book WHERE isbn = ?";
        try (Connection connection = DbConfig.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {

            preparedStatement.setString(1, isbn);
            ResultSet objRest = preparedStatement.executeQuery();

            if (objRest.next()) {
                Book book = new Book();
                book.setIdBook(objRest.getInt("id_book"));
                book.setTitle(objRest.getString("title"));
                book.setAuthor(objRest.getString("author"));
                book.setIsbn(objRest.getString("isbn"));
                book.setStock(objRest.getInt("stock"));
                book.setStatus(objRest.getBoolean("status"));

                return Optional.of(book);
            }

        } catch (SQLException e) {
            throw new DataAccessException("Error searching for book by ID", e);
        }
        return Optional.empty();
    }

    @Override
    public List<Book> findAll() throws DataAccessException {

        List<Book> books = new ArrayList<>();
        String sql = "SELECT * FROM book ORDER BY title ASC";

        try (Connection connection = DbConfig.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql);
             ResultSet objRest = preparedStatement.executeQuery()) {

            while (objRest.next()) {
                Book book = new Book();
                book.setIdBook(objRest.getInt("id_book"));
                book.setTitle(objRest.getString("title"));
                book.setAuthor(objRest.getString("author"));
                book.setIsbn(objRest.getString("isbn"));
                book.setStock(objRest.getInt("stock"));
                book.setStatus(objRest.getBoolean("status"));
                books.add(book);
            }
        } catch (SQLException e) {
            throw new DataAccessException("Error finding all books", e);
        }
        return books;
    }

    @Override
    public void update(Book book) throws DataAccessException {
        String sql = "UPDATE book SET title = ?, author = ?, isbn = ?, stock = ?, status = ? WHERE id_book = ?";
        try (Connection connection = DbConfig.getConnection()) { // Obtiene su propia conexión
            update(book, connection); // Llama al metodo que hace el trabajo real
        } catch (SQLException e) {
            throw new DataAccessException("Error getting connection for book update", e);
        }
    }

    @Override
    public void update(Book book, Connection connection) throws DataAccessException {
        String sql = "UPDATE book SET title = ?, author = ?, isbn = ?, stock = ?, status = ? WHERE id_book = ?";
        // NO uses try-with-resources para la conexión aquí, porque no debes cerrarla
        try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
            preparedStatement.setString(1, book.getTitle());
            preparedStatement.setString(2, book.getAuthor());
            preparedStatement.setString(3, book.getIsbn());
            preparedStatement.setInt(4, book.getStock());
            preparedStatement.setBoolean(5, book.isStatus());
            preparedStatement.setInt(6, book.getIdBook());

            if (preparedStatement.executeUpdate() == 0) {
                throw new DataAccessException("Updating book failed, no rows affected. ID: " + book.getIdBook());
            }
        } catch (SQLException e) {
            // La excepción ahora será más específica y será capturada por el servicio
            throw new DataAccessException("Error updating book with ID " + book.getIdBook(), e);
        }
    }

    @Override
    public void delete(Integer id) throws DataAccessException {
        String sql = "DELETE FROM book WHERE id_book = ?";

        try (Connection connection = DbConfig.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {

            preparedStatement.setInt(1, id);
            int affectedRows = preparedStatement.executeUpdate();

            if (affectedRows == 0) {
                throw new DataAccessException("Deleting book failed, no rows affected");
            }
        } catch (SQLException e) {
            throw new DataAccessException("Error deleting book with ID " + id, e);
        }
    }


}