package dao.impl;

import config.DbConfig;
import dao.interfaces.LoanDao;
import domain.*;
import exception.DataAccessException;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class LoanDaoImpl implements LoanDao {

    @Override
    public Loan createLoan(Loan loan) throws DataAccessException {

        // Sintaxis to create the loan
        String sqlLoan = "INSERT INTO loan (id_user, id_book, id_member, id_status, loan_date, return_date) VALUES (?, ?, ?, ?, ?, ?)";
        // Sintaxis to subtract 1 from the book stock, validating that there are units available
        String sqlUpdateBook = "UPDATE book SET stock = stock - 1 WHERE id_book = ? AND stock > 0";

        Connection connection = null;
        try {
            connection = DbConfig.getConnection();
            // setAutoCommit gets conexion and Disable autocommit because this method performs two dependent operations
            // -Subtract the stock -Insert the loan
            connection.setAutoCommit(false); // Start Transaction

            // The book stock is updated
            try (PreparedStatement preparedStatementUpdate = connection.prepareStatement(sqlUpdateBook)) { // This runs the query to decrease stock
                preparedStatementUpdate.setInt(1, loan.getBook().getIdBook());
                if (preparedStatementUpdate.executeUpdate() == 0) {
                    throw new SQLException("Book out of stock or does not exist");
                }
            }

            // Create the loan record
            try (PreparedStatement prepareStatementLoan = connection.prepareStatement(sqlLoan, Statement.RETURN_GENERATED_KEYS)) {
                prepareStatementLoan.setInt(1, loan.getUser().getIdUser());
                prepareStatementLoan.setInt(2, loan.getBook().getIdBook());
                prepareStatementLoan.setInt(3, loan.getMember().getIdMember());
                prepareStatementLoan.setInt(4, loan.getStatus().getIdStatus());
                prepareStatementLoan.setDate(5, Date.valueOf(loan.getLoanDate()));
                prepareStatementLoan.setDate(6, Date.valueOf(loan.getReturnDate()));

                prepareStatementLoan.executeUpdate();

                // Use Statement.RETURN_GENERATED_KEYS to retrieve the id_loan autogenerated by the DB
                try (ResultSet objRest = prepareStatementLoan.getGeneratedKeys()) {
                    if (objRest.next()) {
                        loan.setIdLoan(objRest.getInt(1));
                    }
                }
            }
            // If all is OK, commit the transaction
            connection.commit();
            return loan;

        } catch (SQLException e) {
            // If anything fails, roll back
            if (connection != null) {
                try {
                    connection.rollback();
                } catch (SQLException error) {
                    throw new DataAccessException("Error during rollback", error);
                }
            }
            throw new DataAccessException("Error creating loan, transaction rolled back", e);
        } finally { // Normal state is restored
            // Restore autocommit and close connection
            if (connection != null) {
                try {
                    connection.setAutoCommit(true);
                    connection.close();
                } catch (SQLException e) {
                    // Log this error
                    e.printStackTrace();
                }
            }
        }
    }

    @Override
    public Optional<Loan> findById(int id) throws DataAccessException {
        String sql = getBaseSelectQuery() + " WHERE l.id_loan = ?";
        List<Loan> loans = findLoansByQuery(sql, id); // returns a list of loans
        return loans.isEmpty() ? Optional.empty() : Optional.of(loans.get(0)); // ternary operator
    }

    @Override
    public void update(Loan loan) throws DataAccessException {
        // Obtenemos una nueva conexión y la cerramos aquí mismo
        try (Connection connection = DbConfig.getConnection()) {
            // Llamamos al método que contiene la lógica real, pasándole la conexión
            update(loan, connection);
        } catch (SQLException e) {
            throw new DataAccessException("Error getting connection for loan update", e);
        }
    }

    @Override
    public void update(Loan loan, Connection connection) throws DataAccessException {
        // This is typically used for returning a book
        String sql = "UPDATE loan SET id_status = ?, actual_return_date = ?, fine = ? WHERE id_loan = ?";
        try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
            preparedStatement.setInt(1, loan.getStatus().getIdStatus());
            // handle possible null value for actualReturnDate
            if (loan.getActualReturn() != null) {
                preparedStatement.setDate(2, Date.valueOf(loan.getActualReturn()));
            } else {
                preparedStatement.setNull(2, Types.DATE);
            }
            preparedStatement.setBigDecimal(3, loan.getFine());
            preparedStatement.setInt(4, loan.getIdLoan());

            if (preparedStatement.executeUpdate() == 0) {
                throw new DataAccessException("Loan update failed, no rows affected for ID: " + loan.getIdLoan());
            }
        } catch (SQLException e) {
            throw new DataAccessException("Error updating loan" + loan.getIdLoan(), e);
        }
    }

    @Override
    public List<Loan> findAll() throws DataAccessException {
        return findLoansByQuery(getBaseSelectQuery());
    }

    // overdue loans -> vencido
    // Returns loans whose repayment date has passed and don't have an actual return date, meaning they're still outstanding perfect for displaying alerts or calculating penalties
    @Override
    public List<Loan> findOverdueLoans() throws DataAccessException {
        // Find loans that are past their return date and have not been returned yet
        String sql = getBaseSelectQuery() + " WHERE l.return_date < CURRENT_DATE AND l.actual_return_date IS NULL";
        return findLoansByQuery(sql);
    }

    // OJO: Helper Methods to avoid code duplication
    private String getBaseSelectQuery() {
        // This query uses JOINs to fetch all related data in a single database call
        return "SELECT l.id_loan, l.loan_date, l.return_date, l.actual_return_date, l.fine, " +
                "u.id_user, u.username, " +
                "b.id_book, b.title, " +
                "m.id_member, m.full_name, " +
                "s.id_status, s.name as status_name " +
                "FROM loan l " +
                "JOIN users u ON l.id_user = u.id_user " +
                "JOIN book b ON l.id_book = b.id_book " +
                "JOIN member m ON l.id_member = m.id_member " +
                "JOIN loan_status s ON l.id_status = s.id_status";
    }

    // reusable method to execute queries
    private List<Loan> findLoansByQuery(String sql, Object... params) throws DataAccessException {
        List<Loan> loans = new ArrayList<>();
        try (Connection connection = DbConfig.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {

            for (int i = 0; i < params.length; i++) {
                preparedStatement.setObject(i + 1, params[i]);
            }

            try (ResultSet objRest = preparedStatement.executeQuery()) {
                while (objRest.next()) {
                    loans.add(mapResultSetToLoan(objRest));
                }
            }
        } catch (SQLException e) {
            throw new DataAccessException("Error executing loan query.", e);
        }
        return loans;
    }

    // build Loan object from DB
    private Loan mapResultSetToLoan(ResultSet objRest) throws SQLException {
        Loan loan = new Loan();
        loan.setIdLoan(objRest.getInt("id_loan"));
        loan.setLoanDate(objRest.getDate("loan_date").toLocalDate());
        loan.setReturnDate(objRest.getDate("return_date").toLocalDate());
        Date actualReturn = objRest.getDate("actual_return_date");
        if (actualReturn != null) {
            loan.setActualReturn(actualReturn.toLocalDate());
        }
        loan.setFine(objRest.getBigDecimal("fine"));

        User user = new User();
        user.setIdUser(objRest.getInt("id_user"));
        user.setUsername(objRest.getString("username"));
        loan.setUser(user);

        Book book = new Book();
        book.setIdBook(objRest.getInt("id_book"));
        book.setTitle(objRest.getString("title"));
        loan.setBook(book);

        Member member = new Member();
        member.setIdMember(objRest.getInt("id_member"));
        member.setFullName(objRest.getString("full_name"));
        loan.setMember(member);

        Status status = new Status();
        status.setIdStatus(objRest.getInt("id_status"));
        status.setName(objRest.getString("status_name"));
        loan.setStatus(status);

        return loan;
    }
}
