package dao.impl;

import config.DbConfig;
import dao.interfaces.UserDao;
import domain.Role;
import domain.User;
import exception.DataAccessException;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class UserDaoImpl implements UserDao {

    @Override
    public User create(User user) throws DataAccessException {
        String sql = "INSERT INTO users (id_role, username, email, password, status) VALUES (?, ?, ?, ?, ?)";

        // Prepare the statement to enter the data, also add the return generated keys to return the id generated by the database
        try (Connection connection = DbConfig.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            preparedStatement.setInt(1, user.getRole().getIdRole());
            preparedStatement.setString(2, user.getUsername());
            preparedStatement.setString(3, user.getEmail());
            preparedStatement.setString(4, user.getPassword());
            preparedStatement.setBoolean(5, user.isStatus());

            if (preparedStatement.executeUpdate() == 0) {
                throw new DataAccessException("The creation of the user failed");
            }

            try (ResultSet objRestKeys = preparedStatement.getGeneratedKeys()) {
                if (objRestKeys.next()) {
                    user.setIdUser(objRestKeys.getInt(1));
                } else {
                    throw new DataAccessException("Failed to create user, could not get ID");
                }
            }
            return user;
        } catch (SQLException e) {
            throw new DataAccessException("Error creating book in the database", e);
        }
    }

    @Override
    public Optional<User> findById(Integer id) throws DataAccessException {
        String sql = getBaseSelectQuery() + " WHERE u.id_user = ?";

        try (Connection connection = DbConfig.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {

            preparedStatement.setInt(1, id);

            try (ResultSet objRest = preparedStatement.executeQuery()) {
                if (objRest.next()) {
                    return Optional.of(mapResultSetToUser(objRest));
                }
            }

        } catch (SQLException e) {
            throw new DataAccessException("Error searching for user by ID", e);
        }
        return Optional.empty();
    }

    @Override
    public Optional<User> findByNameUser(String username) throws DataAccessException {
        String sql = getBaseSelectQuery() + " WHERE u.username = ?";

        try (Connection connection = DbConfig.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {

            preparedStatement.setString(1, username);

            try (ResultSet objRest = preparedStatement.executeQuery()) {
                if (objRest.next()) {
                    return Optional.of(mapResultSetToUser(objRest));
                }
            }

        } catch (SQLException e) {
            throw new DataAccessException("Error searching for user by username", e);
        }
        return Optional.empty();
    }

    @Override
    public List<User> findAll() throws DataAccessException {
        List<User> users = new ArrayList<>();
        String sql = getBaseSelectQuery() + " ORDER BY u.username";

        try (Connection connection = DbConfig.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql);
             ResultSet objRest = preparedStatement.executeQuery()) {
            while (objRest.next()) {
                users.add(mapResultSetToUser(objRest));
            }
        } catch (SQLException e) {
            throw new DataAccessException("Error finding all users", e);
        }
        return users;
    }

    @Override
    public void update(User user) throws DataAccessException {
        String sql = "UPDATE users SET id_role = ?, username = ?, email = ?, password = ?, status = ? WHERE id_user = ?";

        try (Connection connection = DbConfig.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {

            preparedStatement.setInt(1, user.getRole().getIdRole());
            preparedStatement.setString(2, user.getUsername());
            preparedStatement.setString(3, user.getEmail());
            preparedStatement.setString(4, user.getPassword());
            preparedStatement.setBoolean(5, user.isStatus());
            preparedStatement.setInt(6, user.getIdUser());

            int affectedRows = preparedStatement.executeUpdate();
            if (affectedRows == 0) {
                throw new DataAccessException("User update failed, user not found");
            }
        } catch (SQLException e) {
            throw new DataAccessException("Error updating user " + user.getIdUser(), e);
        }
    }

    @Override
    public void delete(Integer id) throws DataAccessException {
        String sql = "DELETE FROM users WHERE id_user = ?";

        try (Connection connection = DbConfig.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {

            preparedStatement.setInt(1, id);
            int affectedRows = preparedStatement.executeUpdate();

            if (affectedRows == 0) {
                throw new DataAccessException("User deletion failed");
            }
        } catch (SQLException e) {
            throw new DataAccessException("Error deleting user " + id, e);
        }
    }

    private String getBaseSelectQuery() {
        return "SELECT u.id_user, u.username, u.email, u.password, u.status, " +
                "r.idRole, r.typeRol " +
                "FROM users u " +
                "JOIN Role r ON u.id_role = r.idRole";
    }

    private User mapResultSetToUser(ResultSet objRest) throws SQLException {
        Role role = new Role(objRest.getInt("idRole"), objRest.getString("typeRol"));
        return new User(
                objRest.getInt("id_user"),
                role,
                objRest.getString("username"),
                objRest.getString("email"),
                objRest.getString("password"),
                objRest.getBoolean("status")
        );
    }
}