# App info
spring.application.name=camila-acosta-mobileFix
server.port=8080

# views JSP
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# DB H2
spring.datasource.url=jdbc:h2:mem:mobilefixdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA -> persistencia
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Console H2 (only develop)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
